version: "3.7"

services:
  vscode:
    build: .
    volumes:
      - ../:/workspace
      # Docker
      - ~/.docker:/home/vscode/.docker
      # Docker socket to access Docker server
      - /var/run/docker.sock:/var/run/docker.sock
      # Shell history persistence
      - ~/.zsh_history:/home/vscode/.zsh_history
      # Git config
      - ~/.gitconfig:/home/vscode/.gitconfig
    environment:
      - TZ=
    entrypoint: [ "zsh", "-c", "while sleep 1000; do :; done" ]
  database:
    image: postgres
    restart: always
    env_file: ../.env
