name: CD

on:
  push:
    branches: [ "main" ]

jobs:
  validate:
    uses: ./.github/workflows/validate.yaml
    secrets: inherit
  deploy:
    uses: ./.github/workflows/deploy.yaml
    needs: validate
    secrets: inherit
